[package]
name = "tower-reqwest"
description = "Adapter between reqwest and tower-http crates."

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["util", "reqwest-middleware"]
reqwest-middleware = ["dep:reqwest-middleware"]
util = []

[dependencies]
futures-util = "0.3"
http = "1.0"
http-body-util = "0.1"
hyper = { version = "1.0" }
include-utils = "0.2"
log = "0.4"
pin-project = "1.0"
reqwest = { version = "0.12", features = ["stream"] }
reqwest-middleware = { version = "0.3.0", optional = true }
thiserror = "1.0"
tower = { version = "0.4" }
tower-http = { version = "0.5", features = ["set-header", "util", "request-id"] }

[dev-dependencies]
anyhow = "1.0"
pretty_assertions = "1.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
wiremock = "0.6.0"

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
